version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - REDIS_URL=redis://redis:6379/0
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=please-change
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - redis
      - neo4j
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "aiteam.asgi:application"]

  worker:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=aiteam.settings
    depends_on:
      - redis
    command: ["celery", "-A", "aiteam", "worker", "-l", "INFO"]

  beat:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=aiteam.settings
    depends_on:
      - redis
    command: ["celery", "-A", "aiteam", "beat", "-l", "INFO"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/please-change
    ports:
      - "7474:7474"
      - "7687:7687"

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama:
